# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.IntegerField(),
        ),
    ]
