# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_auto_20170714_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='name',
        ),
    ]
