# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0010_path5_path6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('dep_hr', models.IntegerField(max_length=3)),
                ('dep_min', models.IntegerField(max_length=3)),
                ('arr_hr', models.IntegerField(max_length=3)),
                ('arr_min', models.IntegerField(max_length=3)),
                ('stoppage', models.IntegerField(max_length=5)),
            ],
        ),
    ]
