# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0014_path8'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('dep_hr', models.IntegerField()),
                ('dep_min', models.IntegerField()),
                ('arr_hr', models.IntegerField()),
                ('arr_min', models.IntegerField()),
                ('stoppage', models.IntegerField()),
            ],
        ),
    ]
